pallet_p_options:
- initial: true
  name: Waiting for ready product to hold
  value: idle
- initial: false
  name: Robot's movement towards product
  value: a
- initial: false
  name: Gripper latches
  value: b
- initial: false
  name: Product is up
  value: c
- initial: false
  name: Robot's movement towards pallet
  value: d
- initial: false
  name: Gripper opens
  value: e
- initial: false
  name: Product is released
  value: f
sub_options:
- initial: true
  name: Waiting for palletization process to start
  value: idle
- initial: false
  name: Waiting for product to arrive
  value: a
- initial: false
  name: Product is ready to hold
  value: b
- initial: false
  name: Product is up
  value: c
supervisor_options:
- initial: true
  name: IDLE
  value: idle
- initial: false
  name: Waiting for empty pallet to arrive
  value: a
- initial: false
  name: Palletizing process
  value: b
- initial: false
  name: Waiting for full pallet to exit
  value: c
